### ISSUE TITLE
State machine instance containing multiple State properties errors unless InstanceState defined

### ISSUE THREAD

**Issue by BrianHarboldt** [MassTransit/Automatonymous#18]
version: 3.0.4-beta

If the instance object for a state machine contains more than one State the `InstanceState()` must be used, even if `CurrentState` is available.
A `System.NullReferenceException` is thrown if InstanceState is omitted.

**Comment by phatboyg** [comment]
Interesting. The auto-discovery fails if there are multiple state properties, but since it's specified in the constructor after the base class has initialized, there isn't really a hook to check if it's been specified. I suppose before actually doing anything (such as wiring up to the saga repository or something) that the value should be checked and if the Accessor is null, throwing a different exception type.

**Comment by phatboyg** [comment]
I'm pretty sure this was addressed, because I saw it the other day when working on an issue.
