### ISSUE TITLE
Does Automatonymous supports commands? 

### ISSUE THREAD

**Issue by yahya99223** [MassTransit/Automatonymous#39]
Instead of events being raised between services coming and going I want to use commands where the first service commands the second specific service to do something and wait for response.
saw that you have documentation [here](http://automatonymous.readthedocs.io/en/latest/overview/request.html?highlight=request)
but it is poor and machine state is not used.
I might have said something wrong because I am new to the whole messaging between services idea.
thanks

**Comment by phatboyg** [comment]
You can use a state machine to handle a request/command, it's just initiated with a command instead of an event. In state machine configuration, it's still an `Event<T>` - it's really just a message. The "event" is the receipt of the message, regardless of the type of message received on the queue.

If you need to respond to a message, save the RequestId header, the ResponseAddress header, and use them to send the response once the state machine completes.
